<form action="login/validate" method="POST">
    <input name="username" type="text" placeholder="Username"/>
    <input name="password" type="password" placeholder="Password"/>
    <input type="submit" value="Log In" />
    
    Username must be between <?php \RootCmsAuth\Controller\RootCmsAuthController::MIN_USERNAME_LEN ?>
    and <?php \RootCmsAuth\Controller\RootCmsAuthController::MAX_USERNAME_LEN ?> long containing only 
    letters, numbers or underscore.
    
    
</form>